[applications.official]
browser=["brave"]
reader=["okular"]
editor=["neovim"]
im=["linuxqq","telegram-desktop"]
ime=["fcitx5","fcitx5-rime","fcitx5-qt","fcitx5-gtk","fcitx5-configtool"]
version-control=["jujutsu","git"]
utils=["yazi"]
reversing=["radare2"]
[applications.archlinuxcn]

[dev-tools.nvim]
lsp=["node"]


[applications.aur]
ime=["fcitx5-themes-candlelight"]
editor=["visual-studio-code-bin"]
os-dev=["i386-elf-gcc"]
pager=["nvimpager"]


[languages]
racket.packages=["sicp","eopl","racket-langserver"]

[create_dir]
yt-dlp=["~/Videos/ytb/"]
