[applications.official]
browser=["brave"]
reader=["okular"]
im=["linuxqq","telegram-desktop"]
ime=["fcitx5","fcitx5-rime","fcitx5-qt","fcitx5-gtk","fcitx5-configtool"]
vsc=["jujutsu","git"]

[dev-tools.nvim]
lsp=["node"]





[applications.aur]
ime=["fcitx5-themes-candlelight"]
dev-tools=["visual-studio-code-bin"]
os-dev=["i386-elf-gcc"]



[languages]
racket.packages=["sicp","eopl","racket-langserver"]

[create]
yt-dlp=["~/Videos/ytb/"]
